---
layout: post
title: 코루틴에서의 예외 처리
subtitle: 예외 처리
published: true
categories: [Kotlin, Coroutines]
tags: [Kotlin, Coroutines]
---

## 프로그래밍에서 예외 처리가 중요하듯이, 코루틴에서도 아주 중요하다

> 코루틴에서 예외가 발생하면, 부모 코루틴에게 예외가 **전파**되어 부모가 취소되며 다른 자식도 모두 취소된다

```
fun main(): Unit = runBlocking {
    // A
    launch {
        // B
        launch {
            delay(100)
            throw Error("B Some Error")
        }

        // C
        launch {
            delay(200)
            println("C 출력안됨")
        }

        // D
        launch {
            delay(300)
            println("D 출력안됨")
        }
    }

    // E
    launch {
        delay(400)
        println("E 출력안됨")
    }
}

Exception in thread "DefaultDispatcher-worker-1" java.lang.Error: B Some Error
```

`B`에서 발생한 예외가 루트까지 전파되고, 모두 취소되는 흐름


![코루틴 예외 drawio](https://github-production-user-asset-6210df.s3.amazonaws.com/48265129/282290539-be234556-aada-4b9e-a1a0-c3149346f1e8.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231112T121826Z&X-Amz-Expires=300&X-Amz-Signature=9d67c494b023321e29046921bd5a14d185d9334205e5930d97f63a3f657b55af&X-Amz-SignedHeaders=host&actor_id=48265129&key_id=0&repo_id=685439824)


## 코루틴 종료 멈추기

> 계층이 있는 코루틴에 대해서는 `try-catch`를 사용하여 예외를 처리할 수 없다

아래와 같이 `try-catch`를 쓰더라도 해당 구문이 무시되어 처리가 되지 않는다

```
try {
    // B
    launch {
        delay(1000)
        throw Error("Some Error") // 출력됨
    }
} catch (e: Exception) {
    println("출력되지 않음")
}
```

### 대안 1 : SupervisorJob

> `SupervisorJob`를 사용하는 코루틴은 다른 코루틴에게 영향을 주지 않는다

- SupervisorJob : 부모 코루틴과의 연결을 느슨하게 만들어 해당 코루틴에서 발생한 예외가 부모와 형제 코루틴에게 영향을 주지않는다
- Job : 기본 유형, 부모와 강하게 연결되어 있어 해당 코루틴에서 발생한 예외가 부모와 형제 코루틴에게 영향을 준다

```
fun main(): Unit = runBlocking {
    val scope = CoroutineScope(SupervisorJob())
    
    scope.launch {
        // B
        delay(100)
        throw Error("B Some Error")
    }

    // C
    launch {
        delay(200)
        println("C 출력됨")
    }

    // D
    launch {
        delay(300)
        println("D 출력됨")
    }
    

    // E
    launch {
        delay(400)
        println("E 출력됨")
    }
}

Exception in thread "DefaultDispatcher-worker-1" java.lang.Error: B Some Error
C 출력됨
D 출력됨
E 출력됨
```


![코루틴 예외-supervisorjob drawio](https://github-production-user-asset-6210df.s3.amazonaws.com/48265129/282290863-ed345288-77a6-423e-9c6e-fbef19c322e3.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231112T121838Z&X-Amz-Expires=300&X-Amz-Signature=73a47e33bae75b2eea555eb7c8511ae3b80150f04a6c577e5eb72b0586a712f7&X-Amz-SignedHeaders=host&actor_id=48265129&key_id=0&repo_id=685439824)


### 대안 2 : supervisorScope

> `supervisorScope`내의 코루틴은 서로 독립적으로 동작하여, 예외가 발생해도 다른 코루틴에게 영향을 주지 않는다


- 독립적인 자식 코루틴 : supervisorScope내의 코루틴들은 각각 독립적으로 동작한다
- 상위 Scope가 안전 : supervisorScope내의 예외는 상위 Scope에 영향을 주지 않는다

```
fun main(): Unit = runBlocking {
    supervisorScope {
        launch {
            // B
            delay(100)
            throw Error("B Some Error")
        }

        // C
        launch {
            delay(200)
            println("C 출력됨")
        }

        // D
        launch {
            delay(300)
            println("D 출력됨")
        }
    }

    // E
    launch {
        delay(400)
        println("E 출력됨")
    }
}

Exception in thread "main" java.lang.Error: B Some Error
C 출력됨
D 출력됨
E 출력됨
```

- `async`를 사용하더라도 독립적인 코루틴이므로 서로 영향을 주지 않는다

```
suspend fun main() = supervisorScope {
    // B
    val jobB = async {
        delay(100)
        throw Error("B Some Error")
    }

    // C
    val jobC = async {
        delay(200)
        "C"
    }

    // D
    val jobD = async {
        delay(300)
        "D"
    }

    try {
        jobB.await()
    } catch (e: Throwable) {
        println(e.message)
    }
    println(jobC.await())
    println(jobD.await())

    // E
    val jobE = async {
        delay(400)
        "E"
    }
    println(jobE.await())
}

B Some Error
C
D
E
```

#### 사용 예시 : 독립적인 데이터 분석

> 서로 간에 의존이 없는 데이터 분석을 동시에 수행할 때 사용, 하나의 데이터 분석이 실패해도 다른 데이터 분석에 영향을 주지 않아야 하기 때문

```
suspend fun analyzeData(dataList: List<Data>) = 
    supervisorScope {
        dataList.forEach { data ->
            launch {
                val result = analyze(data)
                notifyResult(result)
            }
        }
    }
```

#### `withContext(SupervisorJob())` 사용 금지

> `withContext(SupervisorJob())`를 사용하면, `withContext`내의 코루틴들은 독립적으로 동작하지 않는다

```
suspend fun analyzeData(dataList: List<Data>) = 
    withContext(SupervisorJob()) {
        dataList.forEach { data ->
            launch {
                val result = analyze(data)
                notifyResult(result)
            }
        }
    }
```

withContext의 부모가 SupervisorJob이 되어 하위 코루틴에서 예외가 발생하면 모든 코루틴이 취소된다

![코루틴 예외-supervisorjob의 복사본 drawio](https://github-production-user-asset-6210df.s3.amazonaws.com/48265129/282292159-a424b617-6f5d-4af3-930d-c8d2535b51fc.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231112%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231112T121859Z&X-Amz-Expires=300&X-Amz-Signature=c2531546e1f05770656c2f142563562b2876193d3d79f7249fa1ee50c2056d69&X-Amz-SignedHeaders=host&actor_id=48265129&key_id=0&repo_id=685439824)

## 예외 클래스가 `CancellationException`를 상속받으면 예외가 부모 코루틴으로 전파되지 않음

### 값이 홀수일 때 예외를 발생

예외가 발생하여 부모, 자식 코루틴이 종료된다

```
data class OddException(val value: Int) : Exception()

suspend fun main(): Unit = coroutineScope {
    repeat(100) {
        launch {
            if (it % 2 == 1) {
                throw OddException(it)
            }
            println(it)
        }
    }
}

0
2
4
Exception in thread "main" OddException(value=1)
```

예외 클래스를 `CancellationException`의 하위 클래스로 만들면, 예외는 부모로 전파되지 않고, 예외가 발생한 코루틴만 취소된다

홀수값인 코루틴만 취소되고, 나머지 짝수 코루틴은 정상 동작

```kotlin
data class OddException(val value: Int) : CancellationException()

0
2
4
6
8
10
12
14
...
98
```


## `CoroutineExceptionHandler`로 예외 발생 시 처리가능

> `CoroutineExceptionHandler`를 사용하면, 예외가 발생했을 때의 로직을 처리할 수 있다

```
fun main(): Unit = runBlocking {
    val handler = CoroutineExceptionHandler { _, exception ->
        if (exception is OddException) {
            println("홀수 예외 : ${exception.value}")
        }
    }
    val scope = CoroutineScope(
        SupervisorJob() + handler
    )

    repeat(100) {
        scope.launch { // 각 코루틴에 handler 적용
            if (it % 2 == 1) {
                throw OddException(it)
            }
            println(it)
        }
    }
}

36
38
홀수 예외 : 15
홀수 예외 : 29
40
42
```